dist: xenial

os:
- linux

language: go

go:
- "1.14.x"
- tip

matrix:
  allow_failures:
  - go: tip

cache:
  directories:
    - $GOPATH/pkg/mod

script:
- make test

jobs:
  include:
  - name: "Linting"
    go: "1.14.x"
    env:
    - GOLANGCI_RELEASE="v1.26.0"
    before_install:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_RELEASE}
    script:
    - make lint
  - name: "Coverage"
    go: "1.14.x"
    before_install:
    - GO111MODULE=off go get github.com/mattn/goveralls
    - GO111MODULE=off go get github.com/lawrencewoodman/roveralls
    script:
    - travis_wait 20 roveralls
    - goveralls -coverprofile=roveralls.coverprofile -service=travis-ci
